<!doctype html>
<html lang="en">

<head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS v5.2.1 -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous" />
</head>

<body>
    <header>
        <!-- place navbar here -->
    </header>
    <main>

        <select name="" id="">
            <option value="12 de Julio">12 de Julio</option>
            <option value="15 de Enero">15 de Enero</option>
            <option value="15 de Mayo">15 de Mayo</option>
            <option value="16 de Septiembre">16 de Septiembre</option>
            <option value="1 de Mayo">1 de Mayo</option>
            <option value="1 de Septiembre">1 de Septiembre</option>
            <option value="1 de Septiembre Ampliacion">1 de Septiembre Ampliacion</option>
            <option value="2da. Burocrata">2da. Burocrata</option>
            <option value="3 Jacales">3 Jacales</option>
            <option value="3ra. Burocrata">3ra. Burocrata</option>
            <option value="5 de Mayo">5 de Mayo</option>
            <option value="6 de Enero">6 de Enero</option>
            <option value="6 de Mayo">6 de Mayo</option>
            <option value="9 de Septiembre (CDP)">9 de Septiembre (CDP)</option>
            <option value="Acacias">Acacias</option>
            <option value="Acequias del Sur">Acequias del Sur</option>
            <option value="Adolfo Lopez Mateos">Adolfo Lopez Mateos</option>
            <option value="Adriana">Adriana</option>
            <option value="Aeropuerto">Aeropuerto</option>
            <option value="Aeropuerto Ampliacion">Aeropuerto Ampliacion</option>
            <option value="Agricola Emiliano Zapata">Agricola Emiliano Zapata</option>
            <option value="Aguilas">Aguilas</option>
            <option value="Aguilas de Zaragoza">Aguilas de Zaragoza</option>
            <option value="Aguilas de Zaragoza (IVIECH)">Aguilas de Zaragoza (IVIECH)</option>
            <option value="Agustin Melgar">Agustin Melgar</option>
            <option value="Alameda">Alameda</option>
            <option value="Alamos de San Lorenzo">Alamos de San Lorenzo</option>
            <option value="Alamos de Senecu">Alamos de Senecu</option>
            <option value="Alcazar I (Capri)">Alcazar I (Capri)</option>
            <option value="Alcazar II (Capri)">Alcazar II (Capri)</option>
            <option value="Alfa">Alfa</option>
            <option value="Alondra">Alondra</option>
            <option value="Altamira">Altamira</option>
            <option value="Altavista">Altavista</option>
            <option value="Alvaro Obregon">Alvaro Obregon</option>
            <option value="Amanda">Amanda</option>
            <option value="Americano">Americano</option>
            <option value="Americas">Americas</option>
            <option value="Anahuac">Anahuac</option>
            <option value="Andrea">Andrea</option>
            <option value="Andres Figueroa">Andres Figueroa</option>
            <option value="Anglia Residencial">Anglia Residencial</option>
            <option value="Anita">Anita</option>
            <option value="Antares">Antares</option>
            <option value="Anzures">Anzures</option>
            <option value="Arboleda">Arboleda</option>
            <option value="Arboleda San Fernando">Arboleda San Fernando</option>
            <option value="Arboledas de Senecu">Arboledas de Senecu</option>
            <option value="Arciniega">Arciniega</option>
            <option value="Arcoiris">Arcoiris</option>
            <option value="Arecco">Arecco</option>
            <option value="Arroyo Colorado">Arroyo Colorado</option>
            <option value="Arroyo del Paraiso">Arroyo del Paraiso</option>
            <option value="Arturo Gamiz">Arturo Gamiz</option>
            <option value="Asturias">Asturias</option>
            <option value="Atenas">Atenas</option>
            <option value="Atenas II">Atenas II</option>
            <option value="Aurora">Aurora</option>
            <option value="Avinon">Avinon</option>
            <option value="Azteca">Azteca</option>
            <option value="Banus 360">Banus 360</option>
            <option value="Barrio Alto">Barrio Alto</option>
            <option value="Barrio Azul">Barrio Azul</option>
            <option value="Barrio Hierro">Barrio Hierro</option>
            <option value="Barrio Nuevo">Barrio Nuevo</option>
            <option value="Bella Provincia">Bella Provincia</option>
            <option value="Bella Vista">Bella Vista</option>
            <option value="Bello Horizonte">Bello Horizonte</option>
            <option value="Benito Juarez">Benito Juarez</option>
            <option value="Bilbao">Bilbao</option>
            <option value="Boca del Rio">Boca del Rio</option>
            <option value="Bonanza Residencial">Bonanza Residencial</option>
            <option value="Bosque Bonito">Bosque Bonito</option>
            <option value="Bosques del Sol">Bosques del Sol</option>
            <option value="Bosques del Valle">Bosques del Valle</option>
            <option value="Bosques de Maple">Bosques de Maple</option>
            <option value="Bosques de Salvarcar">Bosques de Salvarcar</option>
            <option value="Bosques de San Jose">Bosques de San Jose</option>
            <option value="Bosques de Santa Fe">Bosques de Santa Fe</option>
            <option value="Bosques de Senecu">Bosques de Senecu</option>
            <option value="Bosques de Sicomoro">Bosques de Sicomoro</option>
            <option value="Bosques de Waterfill">Bosques de Waterfill</option>
            <option value="Bosques Residencial">Bosques Residencial</option>
            <option value="Britania">Britania</option>
            <option value="Buendia">Buendia</option>
            <option value="Buenos Aires">Buenos Aires</option>
            <option value="Bugambilias">Bugambilias</option>
            <option value="Burocrata">Burocrata</option>
            <option value="Burocrata Municipal">Burocrata Municipal</option>
            <option value="Calzada del Sol">Calzada del Sol</option>
            <option value="Camino Real">Camino Real</option>
            <option value="Campestre">Campestre</option>
            <option value="Campestre Ampliacion">Campestre Ampliacion</option>
            <option value="Campestre Arboleda">Campestre Arboleda</option>
            <option value="Campestre las Palmas">Campestre las Palmas</option>
            <option value="Campestre Maria Isabel">Campestre Maria Isabel</option>
            <option value="Campestre San Marcos">Campestre San Marcos</option>
            <option value="Campestre Sur">Campestre Sur</option>
            <option value="Campestre Virreyes">Campestre Virreyes</option>
            <option value="Campos Eliseos">Campos Eliseos</option>
            <option value="Canto de Calabria">Canto de Calabria</option>
            <option value="Canto de Catania">Canto de Catania</option>
            <option value="Canto de Murano">Canto de Murano</option>
            <option value="Canto de Toscana">Canto de Toscana</option>
            <option value="Capistrano">Capistrano</option>
            <option value="Carlos Castillo Peraza">Carlos Castillo Peraza</option>
            <option value="Carlos Chavira Becerra">Carlos Chavira Becerra</option>
            <option value="Casitas de Satelite">Casitas de Satelite</option>
            <option value="Catalan">Catalan</option>
            <option value="Cazadores Juarenses">Cazadores Juarenses</option>
            <option value="Centro">Centro</option>
            <option value="Centro Industrial Juarez">Centro Industrial Juarez</option>
            <option value="CERESO y Ciudad Militar">CERESO y Ciudad Militar</option>
            <option value="Cerrada Abedul">Cerrada Abedul</option>
            <option value="Cerrada Andaluz">Cerrada Andaluz</option>
            <option value="Cerrada Arboledas">Cerrada Arboledas</option>
            <option value="Cerrada Basalto">Cerrada Basalto</option>
            <option value="Cerrada de los Cipreses">Cerrada de los Cipreses</option>
            <option value="Cerrada del Sol">Cerrada del Sol</option>
            <option value="Cerrada del Valle">Cerrada del Valle</option>
            <option value="Cerrada de Tarso">Cerrada de Tarso</option>
            <option value="Cerrada los Olivos">Cerrada los Olivos</option>
            <option value="Cerradas de Oriente I">Cerradas de Oriente I</option>
            <option value="Cerradas de Oriente II">Cerradas de Oriente II</option>
            <option value="Cerrada Vinedos">Cerrada Vinedos</option>
            <option value="Chamizal">Chamizal</option>
            <option value="Chavena">Chavena</option>
            <option value="Chavez-Vargas">Chavez-Vargas</option>
            <option value="Che Guevara">Che Guevara</option>
            <option value="Chihuahua">Chihuahua</option>
            <option value="Cibeles">Cibeles</option>
            <option value="Cielo Vista">Cielo Vista</option>
            <option value="Ciudad Juarez (Abraham Gonzalez)">Ciudad Juarez (Abraham Gonzalez)</option>
            <option value="Ciudad Moderna">Ciudad Moderna</option>
            <option value="Ciudad Rio Bravo">Ciudad Rio Bravo</option>
            <option value="Colegio">Colegio</option>
            <option value="Colinas de Juarez">Colinas de Juarez</option>
            <option value="Colinas del Desierto">Colinas del Desierto</option>
            <option value="Colinas del Norte">Colinas del Norte</option>
            <option value="Colinas del Sol">Colinas del Sol</option>
            <option value="Colinas del Sur">Colinas del Sur</option>
            <option value="Colonial">Colonial</option>
            <option value="Del Agua">Del Agua</option>
            <option value="Del Bravo">Del Bravo</option>
            <option value="Del Carmen">Del Carmen</option>
            <option value="Del Encino">Del Encino</option>
            <option value="Del Futuro">Del Futuro</option>
            <option value="Del Maestro">Del Maestro</option>
            <option value="Del Maestro (Deportiva)">Del Maestro (Deportiva)</option>
            <option value="Del Marquez">Del Marquez</option>
            <option value="Del Norte">Del Norte</option>
            <option value="De los Mecanicos">De los Mecanicos</option>
            <option value="Del Palmar">Del Palmar</option>
            <option value="Del Real">Del Real</option>
            <option value="Del Safari 1">Del Safari 1</option>
            <option value="Del Solar">Del Solar</option>
            <option value="Del Valle">Del Valle</option>
            <option value="Demetrio Flores">Demetrio Flores</option>
            <option value="Desarrollo Salvacar">Desarrollo Salvacar</option>
            <option value="Dinamarca">Dinamarca</option>
            <option value="Distrito Soho">Distrito Soho</option>
            <option value="Division del Norte">Division del Norte</option>
            <option value="Don Julio">Don Julio</option>
            <option value="Dunas Residencial">Dunas Residencial</option>
            <option value="Durango">Durango</option>
            <option value="Eco 2000">Eco 2000</option>
            <option value="Edificio Cartagena">Edificio Cartagena</option>
            <option value="Educacion">Educacion</option>
            <option value="Ejido Sauzal">Ejido Sauzal</option>
            <option value="El Barreal">El Barreal</option>
            <option value="El Campanario">El Campanario</option>
            <option value="El Campanario 4 Siglos">El Campanario 4 Siglos</option>
            <option value="El Cid">El Cid</option>
            <option value="El Dorado">El Dorado</option>
            <option value="Electricistas">Electricistas</option>
            <option value="El Fortin">El Fortin</option>
            <option value="El Granjero (Pie de Casa)">El Granjero (Pie de Casa)</option>
            <option value="El Marmol">El Marmol</option>
            <option value="El Mezquital">El Mezquital</option>
            <option value="El Millon">El Millon</option>
            <option value="El Papalote">El Papalote</option>
            <option value="El Paraiso">El Paraiso</option>
            <option value="El Paseo">El Paseo</option>
            <option value="El Pensamiento">El Pensamiento</option>
            <option value="El Portal">El Portal</option>
            <option value="El Roble">El Roble</option>
            <option value="El Sauzal">El Sauzal</option>
            <option value="El Vergel">El Vergel</option>
            <option value="Emiliano Zapata">Emiliano Zapata</option>
            <option value="Era del Valle">Era del Valle</option>
            <option value="Era de San Lorenzo">Era de San Lorenzo</option>
            <option value="Erendira">Erendira</option>
            <option value="Estacion Mendez">Estacion Mendez</option>
            <option value="Estrella del Poniente">Estrella del Poniente</option>
            <option value="Excelencia">Excelencia</option>
            <option value="Ex Hipodromo">Ex Hipodromo</option>
            <option value="Felipe Angeles">Felipe Angeles</option>
            <option value="Felipe Angeles Ampliacion">Felipe Angeles Ampliacion</option>
            <option value="Fernando Baeza M.">Fernando Baeza M.</option>
            <option value="Fidel Avila">Fidel Avila</option>
            <option value="Florecillas">Florecillas</option>
            <option value="Florencia">Florencia</option>
            <option value="Floresta">Floresta</option>
            <option value="Floresta de San Jose">Floresta de San Jose</option>
            <option value="Fovissste Chamizal">Fovissste Chamizal</option>
            <option value="FOVISSSTE Sur">FOVISSSTE Sur</option>
            <option value="Foxconn">Foxconn</option>
            <option value="Francisco I. Madero">Francisco I. Madero</option>
            <option value="Francisco Sarabia">Francisco Sarabia</option>
            <option value="Francisco Villa">Francisco Villa</option>
            <option value="Franja del Rio">Franja del Rio</option>
            <option value="Fray Garcia de San Francisco">Fray Garcia de San Francisco</option>
            <option value="Frida Khalo">Frida Khalo</option>
            <option value="Frontera">Frontera</option>
            <option value="Fronteriza">Fronteriza</option>
            <option value="Fronteriza Ampliacion">Fronteriza Ampliacion</option>
            <option value="Fuentes Copilco">Fuentes Copilco</option>
            <option value="Fuentes de los Nogales">Fuentes de los Nogales</option>
            <option value="Fuentes del Seminario">Fuentes del Seminario</option>
            <option value="Fuentes del Valle">Fuentes del Valle</option>
            <option value="Fundidora">Fundidora</option>
            <option value="Gaby">Gaby</option>
            <option value="Gardeno">Gardeno</option>
            <option value="Genova">Genova</option>
            <option value="Girasoles">Girasoles</option>
            <option value="Granada">Granada</option>
            <option value="Granjas de Chapultepec">Granjas de Chapultepec</option>
            <option value="Granjas del Desierto">Granjas del Desierto</option>
            <option value="Granjas de San Rafael">Granjas de San Rafael</option>
            <option value="Granjas El Progreso">Granjas El Progreso</option>
            <option value="Granjas los Alcaldes">Granjas los Alcaldes</option>
            <option value="Granjas Polo Gamboa">Granjas Polo Gamboa</option>
            <option value="Granjas San Rafael">Granjas San Rafael</option>
            <option value="Granjas Santa Elena">Granjas Santa Elena</option>
            <option value="Granjas Unidas">Granjas Unidas</option>
            <option value="Granjero">Granjero</option>
            <option value="Gregorio M. Solis">Gregorio M. Solis</option>
            <option value="Guadalajara">Guadalajara</option>
            <option value="Gustavo Diaz Ordaz">Gustavo Diaz Ordaz</option>
            <option value="Habitad del Rio">Habitad del Rio</option>
            <option value="Hacienda">Hacienda</option>
            <option value="Hacienda de Aragon">Hacienda de Aragon</option>
            <option value="Hacienda de La Paloma">Hacienda de La Paloma</option>
            <option value="Hacienda de las Torres">Hacienda de las Torres</option>
            <option value="Hacienda de las Torres Universidad">Hacienda de las Torres Universidad</option>
            <option value="Hacienda de las Torres XII - XIII">Hacienda de las Torres XII - XIII</option>
            <option value="Hacienda de los Nogales">Hacienda de los Nogales</option>
            <option value="Hacienda del Rosario">Hacienda del Rosario</option>
            <option value="Hacienda del Sauz">Hacienda del Sauz</option>
            <option value="Hacienda del Sol">Hacienda del Sol</option>
            <option value="Hacienda de San Francisco">Hacienda de San Francisco</option>
            <option value="Hacienda de San Pedro">Hacienda de San Pedro</option>
            <option value="Hacienda Giralda">Hacienda Giralda</option>
            <option value="Hacienda La Cantera">Hacienda La Cantera</option>
            <option value="Hacienda las Lajas">Hacienda las Lajas</option>
            <option value="Hacienda Residencial">Hacienda Residencial</option>
            <option value="Hacienda San Antonio">Hacienda San Antonio</option>
            <option value="Hacienda San Jose">Hacienda San Jose</option>
            <option value="Hacienda San Juan">Hacienda San Juan</option>
            <option value="Hacienda San Paulo">Hacienda San Paulo</option>
            <option value="Hacienda Santa Fe">Hacienda Santa Fe</option>
            <option value="Haciendas del Campanario">Haciendas del Campanario</option>
            <option value="Hacienda Senecu">Hacienda Senecu</option>
            <option value="Harmoni">Harmoni</option>
            <option value="Hermenegildo Galeana">Hermenegildo Galeana</option>
            <option value="Hermila">Hermila</option>
            <option value="Heroes de La Revolucion">Heroes de La Revolucion</option>
            <option value="Heroes de Mexico">Heroes de Mexico</option>
            <option value="Hidalgo">Hidalgo</option>
            <option value="Holanda">Holanda</option>
            <option value="Horizontes del Sur">Horizontes del Sur</option>
            <option value="Ignacio Aldama">Ignacio Aldama</option>
            <option value="Ignacio Allende">Ignacio Allende</option>
            <option value="Independencia II">Independencia II</option>
            <option value="Independencia Sur">Independencia Sur</option>
            <option value="Industrial">Industrial</option>
            <option value="INFONAVIT Ampliacion Aeropuerto">INFONAVIT Ampliacion Aeropuerto</option>
            <option value="INFONAVIT Angel Trias">INFONAVIT Angel Trias</option>
            <option value="INFONAVIT Casas Grandes">INFONAVIT Casas Grandes</option>
            <option value="INFONAVIT El Jarudo">INFONAVIT El Jarudo</option>
            <option value="INFONAVIT Fidel Velazquez">INFONAVIT Fidel Velazquez</option>
            <option value="INFONAVIT Juarez Nuevo">INFONAVIT Juarez Nuevo</option>
            <option value="INFONAVIT Mil Cumbres">INFONAVIT Mil Cumbres</option>
            <option value="INFONAVIT Oasis">INFONAVIT Oasis</option>
            <option value="INFONAVIT Parques Industriales">INFONAVIT Parques Industriales</option>
            <option value="INFONAVIT Salvarcar">INFONAVIT Salvarcar</option>
            <option value="INFONAVIT San Lorenzo">INFONAVIT San Lorenzo</option>
            <option value="INFONAVIT Solidaridad">INFONAVIT Solidaridad</option>
            <option value="INFONAVIT Tecnologico">INFONAVIT Tecnologico</option>
            <option value="Ingeniero Portillo">Ingeniero Portillo</option>
            <option value="Instituto de Ciencias Biomedicas (ICB)">Instituto de Ciencias Biomedicas (ICB)</option>
            <option value="Instituto de Ingenieria y Arquitectura (IIT/IADA)">Instituto de Ingenieria y Arquitectura (IIT/IADA)</option>
            <option value="Insurgentes">Insurgentes</option>
            <option value="Isla del Encanto">Isla del Encanto</option>
            <option value="Ixtapa">Ixtapa</option>
            <option value="Jardin">Jardin</option>
            <option value="Jardin de las Moras">Jardin de las Moras</option>
            <option value="Jardin de Senecu">Jardin de Senecu</option>
            <option value="Jardines Campestre">Jardines Campestre</option>
            <option value="Jardines de Aragon">Jardines de Aragon</option>
            <option value="Jardines de Coyoacan">Jardines de Coyoacan</option>
            <option value="Jardines del Aeropuerto">Jardines del Aeropuerto</option>
            <option value="Jardines del Bosque">Jardines del Bosque</option>
            <option value="Jardines del Lago">Jardines del Lago</option>
            <option value="Jardines del Seminario">Jardines del Seminario</option>
            <option value="Jardines del Valle">Jardines del Valle</option>
            <option value="Jardines del Valle I">Jardines del Valle I</option>
            <option value="Jardines del Valle II">Jardines del Valle II</option>
            <option value="Jardines del Valle III">Jardines del Valle III</option>
            <option value="Jardines de Roma">Jardines de Roma</option>
            <option value="Jardines de San Carlos">Jardines de San Carlos</option>
            <option value="Jardines de San Francisco">Jardines de San Francisco</option>
            <option value="Jardines de San Jose">Jardines de San Jose</option>
            <option value="Jardines de San Marcos">Jardines de San Marcos</option>
            <option value="Jardines de San Miguel">Jardines de San Miguel</option>
            <option value="Jardines de San Pablo">Jardines de San Pablo</option>
            <option value="Jardines de San Patricio">Jardines de San Patricio</option>
            <option value="Jardines de Santa Clara">Jardines de Santa Clara</option>
            <option value="Jardines de Santa Monica">Jardines de Santa Monica</option>
            <option value="Jardines de Satelite">Jardines de Satelite</option>
            <option value="Jardines Residencial">Jardines Residencial</option>
            <option value="Jardines Senecu">Jardines Senecu</option>
            <option value="Jarudo">Jarudo</option>
            <option value="Jasso">Jasso</option>
            <option value="Jazmines">Jazmines</option>
            <option value="Jesus Carranza (La Colorada)">Jesus Carranza (La Colorada)</option>
            <option value="Josefa Ortiz de Dominguez">Josefa Ortiz de Dominguez</option>
            <option value="Jose Maria Pino Suarez">Jose Maria Pino Suarez</option>
            <option value="Jose Marti">Jose Marti</option>
            <option value="Juarez">Juarez</option>
            <option value="Kilometro 20">Kilometro 20</option>
            <option value="Kilometro 20 Jose Maria">Kilometro 20 Jose Maria</option>
            <option value="Kilometro 27">Kilometro 27</option>
            <option value="Kilometro 28">Kilometro 28</option>
            <option value="Kilometro 29">Kilometro 29</option>
            <option value="Kilometro 5">Kilometro 5</option>
            <option value="La Campesina">La Campesina</option>
            <option value="La Canada">La Canada</option>
            <option value="La Cementera">La Cementera</option>
            <option value="La Conquista">La Conquista</option>
            <option value="La Cuesta">La Cuesta</option>
            <option value="La Cuesta II">La Cuesta II</option>
            <option value="Ladrillera Juarez">Ladrillera Juarez</option>
            <option value="Ladrillera Juarez Ampliacion">Ladrillera Juarez Ampliacion</option>
            <option value="Ladrilleros y Caleros">Ladrilleros y Caleros</option>
            <option value="La Florida">La Florida</option>
            <option value="La Fortuna">La Fortuna</option>
            <option value="La Fuente">La Fuente</option>
            <option value="La Galeanita">La Galeanita</option>
            <option value="La Gaviota">La Gaviota</option>
            <option value="La Gran Manzana">La Gran Manzana</option>
            <option value="La Hacienda">La Hacienda</option>
            <option value="La Herradura">La Herradura</option>
            <option value="La Joya">La Joya</option>
            <option value="La Mesita">La Mesita</option>
            <option value="La Moraleja">La Moraleja</option>
            <option value="La Muralla">La Muralla</option>
            <option value="La Nueva Rosita">La Nueva Rosita</option>
            <option value="La Paloma">La Paloma</option>
            <option value="La Parcela">La Parcela</option>
            <option value="La Parroquia">La Parroquia</option>
            <option value="La Perla">La Perla</option>
            <option value="La Playa">La Playa</option>
            <option value="La Presa">La Presa</option>
            <option value="La Raza">La Raza</option>
            <option value="La Rivera">La Rivera</option>
            <option value="La Rosaleda">La Rosaleda</option>
            <option value="La Rosita">La Rosita</option>
            <option value="Las Acequias">Las Acequias</option>
            <option value="Las Aldabas">Las Aldabas</option>
            <option value="Las Almeras">Las Almeras</option>
            <option value="Las Arcadas">Las Arcadas</option>
            <option value="Las Arenas">Las Arenas</option>
            <option value="Las Arenas 2">Las Arenas 2</option>
            <option value="La Sarzana">La Sarzana</option>
            <option value="Las Dunas">Las Dunas</option>
            <option value="Las Flores">Las Flores</option>
            <option value="Las Garzas">Las Garzas</option>
            <option value="Las Gladiolas">Las Gladiolas</option>
            <option value="Las Haciendas">Las Haciendas</option>
            <option value="Las Haciendas Oriente">Las Haciendas Oriente</option>
            <option value="Las Hadas">Las Hadas</option>
            <option value="Las Lomas">Las Lomas</option>
            <option value="Las Lunas">Las Lunas</option>
            <option value="Las Montanas">Las Montanas</option>
            <option value="Las Nueces">Las Nueces</option>
            <option value="Las Palmas">Las Palmas</option>
            <option value="Las Palomas">Las Palomas</option>
            <option value="Las Placitas I">Las Placitas I</option>
            <option value="Las Placitas II">Las Placitas II</option>
            <option value="Las Quintas">Las Quintas</option>
            <option value="Las Torres I y II">Las Torres I y II</option>
            <option value="Lausane">Lausane</option>
            <option value="Lazaro Cardenas">Lazaro Cardenas</option>
            <option value="Lexmark">Lexmark</option>
            <option value="Leyes de Reforma">Leyes de Reforma</option>
            <option value="Libertad">Libertad</option>
            <option value="Lince">Lince</option>
            <option value="Linda Vista">Linda Vista</option>
            <option value="Lisboa">Lisboa</option>
            <option value="Loma Blanca">Loma Blanca</option>
            <option value="Loma Linda">Loma Linda</option>
            <option value="Lomas del Desierto I">Lomas del Desierto I</option>
            <option value="Lomas del Desierto II">Lomas del Desierto II</option>
            <option value="Lomas del Desierto III">Lomas del Desierto III</option>
            <option value="Lomas del Poleo">Lomas del Poleo</option>
            <option value="Lomas del Rey">Lomas del Rey</option>
            <option value="Lomas del Valle">Lomas del Valle</option>
            <option value="Lomas de Morelos">Lomas de Morelos</option>
            <option value="Lomas de San Jose">Lomas de San Jose</option>
            <option value="Los Agaves">Los Agaves</option>
            <option value="Los Alamos">Los Alamos</option>
            <option value="Los Alcaldes Ampliacion">Los Alcaldes Ampliacion</option>
            <option value="Los Alpes">Los Alpes</option>
            <option value="Los Angeles">Los Angeles</option>
            <option value="Los Arcos">Los Arcos</option>
            <option value="Los Bosques">Los Bosques</option>
            <option value="Los Cardenales">Los Cardenales</option>
            <option value="Los Cedros">Los Cedros</option>
            <option value="Los Cipreses">Los Cipreses</option>
            <option value="Los Cisnes">Los Cisnes</option>
            <option value="Los Colorines">Los Colorines</option>
            <option value="Los Frayles">Los Frayles</option>
            <option value="Los Fresnos">Los Fresnos</option>
            <option value="Los Girasoles">Los Girasoles</option>
            <option value="Los Jardines">Los Jardines</option>
            <option value="Los Lagos">Los Lagos</option>
            <option value="Los Laureles">Los Laureles</option>
            <option value="Los Manantiales">Los Manantiales</option>
            <option value="Los Mezquites">Los Mezquites</option>
            <option value="Los Mirlos">Los Mirlos</option>
            <option value="Los Naranjos">Los Naranjos</option>
            <option value="Los Nogales">Los Nogales</option>
            <option value="Los Olivos">Los Olivos</option>
            <option value="Los Olmos">Los Olmos</option>
            <option value="Los Olmos TEC">Los Olmos TEC</option>
            <option value="Los Parques">Los Parques</option>
            <option value="Los Pinos">Los Pinos</option>
            <option value="Los Portales">Los Portales</option>
            <option value="Los Romerales">Los Romerales</option>
            <option value="Los Sauces">Los Sauces</option>
            <option value="Los Saucos">Los Saucos</option>
            <option value="Los Tulipanes">Los Tulipanes</option>
            <option value="Los Virreyes">Los Virreyes</option>
            <option value="Los Volcanes">Los Volcanes</option>
            <option value="Lucio Blanco">Lucio Blanco</option>
            <option value="Lucio Blanco II">Lucio Blanco II</option>
            <option value="Lucio Cabanas">Lucio Cabanas</option>
            <option value="Luis Donaldo Colosio">Luis Donaldo Colosio</option>
            <option value="Luis Echeverria">Luis Echeverria</option>
            <option value="Luis Olague">Luis Olague</option>
            <option value="Maestros Estatales y Federales">Maestros Estatales y Federales</option>
            <option value="Magisterial">Magisterial</option>
            <option value="Magnolia">Magnolia</option>
            <option value="Malaga">Malaga</option>
            <option value="Manuel Gomez Morin">Manuel Gomez Morin</option>
            <option value="Manuel J. Clouthier">Manuel J. Clouthier</option>
            <option value="Manuel Valdez">Manuel Valdez</option>
            <option value="Maquila Thomson">Maquila Thomson</option>
            <option value="Margaritas">Margaritas</option>
            <option value="Maria Isabel">Maria Isabel</option>
            <option value="Mariano Escobedo">Mariano Escobedo</option>
            <option value="Marquis">Marquis</option>
            <option value="Marruecos">Marruecos</option>
            <option value="Mascarenas">Mascarenas</option>
            <option value="Mayas Sur">Mayas Sur</option>
            <option value="Mayorga">Mayorga</option>
            <option value="Medanos">Medanos</option>
            <option value="Melchor Ocampo">Melchor Ocampo</option>
            <option value="Mexico">Mexico</option>
            <option value="Mexico 68">Mexico 68</option>
            <option value="Miguel Auza">Miguel Auza</option>
            <option value="Miguel Enriquez Guzman">Miguel Enriquez Guzman</option>
            <option value="Milan">Milan</option>
            <option value="Mil Cumbres">Mil Cumbres</option>
            <option value="Minerva">Minerva</option>
            <option value="Mirador">Mirador</option>
            <option value="Mision de los Lagos">Mision de los Lagos</option>
            <option value="Mision del Sol">Mision del Sol</option>
            <option value="Mision de San Miguel">Mision de San Miguel</option>
            <option value="Misiones">Misiones</option>
            <option value="Misiones de Creel">Misiones de Creel</option>
            <option value="Misiones del Emir">Misiones del Emir</option>
            <option value="Misiones del Portal">Misiones del Portal</option>
            <option value="Misiones del Real">Misiones del Real</option>
            <option value="Misiones del Sur Residencial">Misiones del Sur Residencial</option>
            <option value="Ramos Aviles">Ramos Aviles</option>
            <option value="Rancho Anapra">Rancho Anapra</option>
            <option value="Raul Garcia">Raul Garcia</option>
            <option value="Real de Guadalupe">Real de Guadalupe</option>
            <option value="Real de las Torres">Real de las Torres</option>
            <option value="Real del Desierto">Real del Desierto</option>
            <option value="Real del Desierto II">Real del Desierto II</option>
            <option value="Real del Sol">Real del Sol</option>
            <option value="Real del Sol II">Real del Sol II</option>
            <option value="Real de San Jose">Real de San Jose</option>
            <option value="Real Waterfill">Real Waterfill</option>
            <option value="Reforma">Reforma</option>
            <option value="Reginaldo Kluche">Reginaldo Kluche</option>
            <option value="Renovacion 92">Renovacion 92</option>
            <option value="Reserva del Valle">Reserva del Valle</option>
            <option value="Residencial Alamedas">Residencial Alamedas</option>
            <option value="Residencial Almendros">Residencial Almendros</option>
            <option value="Residencial Andalucia">Residencial Andalucia</option>
            <option value="Residencial Bugambilias">Residencial Bugambilias</option>
            <option value="Residencial Campestre Senecu">Residencial Campestre Senecu</option>
            <option value="Residencial Coloso">Residencial Coloso</option>
            <option value="Residencial el Papalote">Residencial el Papalote</option>
            <option value="Residencial Florencia">Residencial Florencia</option>
            <option value="Residencial Galgodromo">Residencial Galgodromo</option>
            <option value="Residencial Hacienda">Residencial Hacienda</option>
            <option value="Residencial Insurgentes">Residencial Insurgentes</option>
            <option value="Residencial Ixtapa">Residencial Ixtapa</option>
            <option value="Residencial las Cumbres">Residencial las Cumbres</option>
            <option value="Residencial las Fuentes">Residencial las Fuentes</option>
            <option value="Residencial las Villas">Residencial las Villas</option>
            <option value="Residencial Lausane">Residencial Lausane</option>
            <option value="Residencial La Villa">Residencial La Villa</option>
            <option value="Residencial Maria Isabel">Residencial Maria Isabel</option>
            <option value="Residencial Montecarlo">Residencial Montecarlo</option>
            <option value="Residencial Pueblo del Sol">Residencial Pueblo del Sol</option>
            <option value="Residencial San Francisco">Residencial San Francisco</option>
            <option value="Residencial San Jeronimo">Residencial San Jeronimo</option>
            <option value="Residencial Sendas">Residencial Sendas</option>
            <option value="Residencial Victoria">Residencial Victoria</option>
            <option value="Residencial Villa Jardin">Residencial Villa Jardin</option>
            <option value="Residencial Villas del Bravos">Residencial Villas del Bravos</option>
            <option value="Residencial Villas Loreto">Residencial Villas Loreto</option>
            <option value="Revolucion Mexicana">Revolucion Mexicana</option>
            <option value="Reyna Fabiola">Reyna Fabiola</option>
            <option value="Ricardo Flores Magon">Ricardo Flores Magon</option>
            <option value="Ricardo Montoya">Ricardo Montoya</option>
            <option value="Rinconada de las Flores">Rinconada de las Flores</option>
            <option value="Rinconada de las Torres">Rinconada de las Torres</option>
            <option value="Rinconada de las Torres IV">Rinconada de las Torres IV</option>
            <option value="Rinconada del Rio">Rinconada del Rio</option>
            <option value="Rinconada de San Marcos">Rinconada de San Marcos</option>
            <option value="Rinconada los Nogales">Rinconada los Nogales</option>
            <option value="Rincon del Amanecer">Rincon del Amanecer</option>
            <option value="Rincon de La Mesa">Rincon de La Mesa</option>
            <option value="Rincon de las Flores">Rincon de las Flores</option>
            <option value="Rincon de las Flores II">Rincon de las Flores II</option>
            <option value="Rincon del Cielo">Rincon del Cielo</option>
            <option value="Rincon del Portal">Rincon del Portal</option>
            <option value="Rincon del Rio">Rincon del Rio</option>
            <option value="Rincon del Rio II">Rincon del Rio II</option>
            <option value="Rincon del Seminario">Rincon del Seminario</option>
            <option value="Rincon del Sol">Rincon del Sol</option>
            <option value="Rincon del Solar">Rincon del Solar</option>
            <option value="Rincon del Solar II">Rincon del Solar II</option>
            <option value="Rincon del Sur">Rincon del Sur</option>
            <option value="Rincon del Valle">Rincon del Valle</option>
            <option value="Rincon de Waterfill">Rincon de Waterfill</option>
            <option value="Rincones de Cartagena">Rincones de Cartagena</option>
            <option value="Rincones del Campanario">Rincones del Campanario</option>
            <option value="Rincones del Campestre">Rincones del Campestre</option>
            <option value="Rincones del Valle">Rincones del Valle</option>
            <option value="Rincones de Oriente">Rincones de Oriente</option>
            <option value="Rincones de Salvarcar">Rincones de Salvarcar</option>
            <option value="Rincones de Salvarcar II">Rincones de Salvarcar II</option>
            <option value="Rincones de San Marcos">Rincones de San Marcos</option>
            <option value="Rincones de Santa Fe">Rincones de Santa Fe</option>
            <option value="Rincones de Santa Rita">Rincones de Santa Rita</option>
            <option value="Rio Grande">Rio Grande</option>
            <option value="Rio Grande I - XXV">Rio Grande I - XXV</option>
            <option value="Riveras del Bravo">Riveras del Bravo</option>
            <option value="Riveras del Bravo IX">Riveras del Bravo IX</option>
            <option value="Rodas">Rodas</option>
            <option value="Rodriguez Borunda">Rodriguez Borunda</option>
            <option value="Roma">Roma</option>
            <option value="Roma Poniente">Roma Poniente</option>
            <option value="Ruisenor">Ruisenor</option>
            <option value="Salvarcar">Salvarcar</option>
            <option value="Samalayuca">Samalayuca</option>
            <option value="San Agustin">San Agustin</option>
            <option value="San Angel">San Angel</option>
            <option value="San Antonio">San Antonio</option>
            <option value="San Antonio Senecu">San Antonio Senecu</option>
            <option value="San Borja">San Borja</option>
            <option value="Sandra Lucia">Sandra Lucia</option>
            <option value="San Felipe el Real">San Felipe el Real</option>
            <option value="San Fernando">San Fernando</option>
            <option value="San Isidro Rio Grande">San Isidro Rio Grande</option>
            <option value="San Jeronimo">San Jeronimo</option>
            <option value="San Jose">San Jose</option>
            <option value="San Lorenzo">San Lorenzo</option>
            <option value="San Marcos">San Marcos</option>
            <option value="San Miguel de Allende">San Miguel de Allende</option>
            <option value="San Pablo">San Pablo</option>
            <option value="San Patricio">San Patricio</option>
            <option value="San Pedro">San Pedro</option>
            <option value="San Pedro del Real">San Pedro del Real</option>
            <option value="San Rafael">San Rafael</option>
            <option value="Santa Catalina">Santa Catalina</option>
            <option value="Santa Cecilia">Santa Cecilia</option>
            <option value="Santa Engracia">Santa Engracia</option>
            <option value="Santa Fe">Santa Fe</option>
            <option value="Santa Lucia">Santa Lucia</option>
            <option value="Santa Maria">Santa Maria</option>
            <option value="Santa Martha">Santa Martha</option>
            <option value="Santa Monica">Santa Monica</option>
            <option value="Santa Rosa">Santa Rosa</option>
            <option value="Santa Rosalia">Santa Rosalia</option>
            <option value="Santa Teresa">Santa Teresa</option>
            <option value="San Valentin">San Valentin</option>
            <option value="Sara Lugo">Sara Lugo</option>
            <option value="Satelite">Satelite</option>
            <option value="Senderos del Sol">Senderos del Sol</option>
            <option value="Senderos de Oriente">Senderos de Oriente</option>
            <option value="Senderos de San Isidro">Senderos de San Isidro</option>
            <option value="Senecu I">Senecu I</option>
            <option value="Senecu II">Senecu II</option>
            <option value="Senorial">Senorial</option>
            <option value="Servet">Servet</option>
            <option value="Sevilla">Sevilla</option>
            <option value="Sicomoros">Sicomoros</option>
            <option value="Sierra Grande">Sierra Grande</option>
            <option value="Sierra Vista">Sierra Vista</option>
            <option value="Siglo XXI">Siglo XXI</option>
            <option value="Silvias">Silvias</option>
            <option value="Simon Rodriguez">Simon Rodriguez</option>
            <option value="SOCOCEMA">SOCOCEMA</option>
            <option value="Sol de Mayo">Sol de Mayo</option>
            <option value="Solidaridad">Solidaridad</option>
            <option value="Sor Juana Ines de La Cruz">Sor Juana Ines de La Cruz</option>
            <option value="Stockmeyer">Stockmeyer</option>
            <option value="Suecia">Suecia</option>
            <option value="Suterm">Suterm</option>
            <option value="Tabachines">Tabachines</option>
            <option value="Tarahumaras">Tarahumaras</option>
            <option value="Tarragona">Tarragona</option>
            <option value="TEC de Monterrey">TEC de Monterrey</option>
            <option value="Tecnologico">Tecnologico</option>
            <option value="Telegrafistas">Telegrafistas</option>
            <option value="Terranova">Terranova</option>
            <option value="Terranova Sur">Terranova Sur</option>
            <option value="Terrazas del Valle">Terrazas del Valle</option>
            <option value="Terrenos Nacionales Sur">Terrenos Nacionales Sur</option>
            <option value="Tierra Nueva I Etapa">Tierra Nueva I Etapa</option>
            <option value="Tierra Nueva II Etapa">Tierra Nueva II Etapa</option>
            <option value="Tierra y Libertad">Tierra y Libertad</option>
            <option value="Tiradores del Norte">Tiradores del Norte</option>
            <option value="Tita">Tita</option>
            <option value="Toledo">Toledo</option>
            <option value="Toribio Ortega">Toribio Ortega</option>
            <option value="Torreon">Torreon</option>
            <option value="Torres del PRI">Torres del PRI</option>
            <option value="Torres del Sur">Torres del Sur</option>
            <option value="Trebol Norte">Trebol Norte</option>
            <option value="Trebol Sur">Trebol Sur</option>
            <option value="Tres Fresnos">Tres Fresnos</option>
            <option value="Tres Hermanos Arecco">Tres Hermanos Arecco</option>
            <option value="Tres Torres">Tres Torres</option>
            <option value="U.H. Benito Juarez">U.H. Benito Juarez</option>
            <option value="U.H. Emiliano Zapata">U.H. Emiliano Zapata</option>
            <option value="U.H. Paso del Norte">U.H. Paso del Norte</option>
            <option value="U.H. Reforma">U.H. Reforma</option>
            <option value="Uranga-Unzueta">Uranga-Unzueta</option>
            <option value="Urbi Alameda Versalles">Urbi Alameda Versalles</option>
            <option value="Urbiquinta Granada">Urbiquinta Granada</option>
            <option value="Urbi Quinta Montecarlo">Urbi Quinta Montecarlo</option>
            <option value="Urbivilla Bonita">Urbivilla Bonita</option>
            <option value="Urbivilla del Campo">Urbivilla del Campo</option>
            <option value="Urbivilla del Cedro">Urbivilla del Cedro</option>
            <option value="Urbivilla del Prado">Urbivilla del Prado</option>
            <option value="Urbivilla del Prado I">Urbivilla del Prado I</option>
            <option value="Valladolid">Valladolid</option>
            <option value="Vallarta">Vallarta</option>
            <option value="Valle Alto">Valle Alto</option>
            <option value="Valle de Allende">Valle de Allende</option>
            <option value="Valle del Bravo">Valle del Bravo</option>
            <option value="Valle del Marques">Valle del Marques</option>
            <option value="Valle de los Cantaros">Valle de los Cantaros</option>
            <option value="Valle del Sol">Valle del Sol</option>
            <option value="Valle de Olivos">Valle de Olivos</option>
            <option value="Valle de Santiago">Valle de Santiago</option>
            <option value="Valle Diamante">Valle Diamante</option>
            <option value="Valle Dorado">Valle Dorado</option>
            <option value="Valle Dorado I">Valle Dorado I</option>
            <option value="Valle Dorado II">Valle Dorado II</option>
            <option value="Valle Dorado III">Valle Dorado III</option>
            <option value="Valle Fundadores">Valle Fundadores</option>
            <option value="Valle Oriente">Valle Oriente</option>
            <option value="Valles de America">Valles de America</option>
            <option value="Valle Sur">Valle Sur</option>
            <option value="Valle Verde">Valle Verde</option>
            <option value="Venecia">Venecia</option>
            <option value="Veneciano">Veneciano</option>
            <option value="Veredas del Sol">Veredas del Sol</option>
            <option value="Vergel Satelite I y II">Vergel Satelite I y II</option>
            <option value="Versalles">Versalles</option>
            <option value="Vicente Guerrero">Vicente Guerrero</option>
            <option value="Villa Alegre">Villa Alegre</option>
            <option value="Villa Alegre I, II, III">Villa Alegre I, II, III</option>
            <option value="Villa Bonita">Villa Bonita</option>
            <option value="Villa Colonial">Villa Colonial</option>
            <option value="Villa de La Arboleda">Villa de La Arboleda</option>
            <option value="Villa del Lago">Villa del Lago</option>
            <option value="Villa del Norte">Villa del Norte</option>
            <option value="Villa Esperanza">Villa Esperanza</option>
            <option value="Villahermosa">Villahermosa</option>
            <option value="Villa Jacarandas">Villa Jacarandas</option>
            <option value="Villa Jardin">Villa Jardin</option>
            <option value="Villa Manzanares">Villa Manzanares</option>
            <option value="Villa Marcela">Villa Marcela</option>
            <option value="Villa Mexicana">Villa Mexicana</option>
            <option value="Villa Residencial del Real">Villa Residencial del Real</option>
            <option value="Villas Adlin">Villas Adlin</option>
            <option value="Villas Anitas">Villas Anitas</option>
            <option value="Villa San Pablo">Villa San Pablo</option>
            <option value="Villas Cerezmy">Villas Cerezmy</option>
            <option value="Villas Conifer">Villas Conifer</option>
            <option value="Villas de Alcala">Villas de Alcala</option>
            <option value="Villas del Bravo I">Villas del Bravo I</option>
            <option value="Villas del Granero">Villas del Granero</option>
            <option value="Villas del Lobo">Villas del Lobo</option>
            <option value="Villas del Rio">Villas del Rio</option>
            <option value="Villas del Solar">Villas del Solar</option>
            <option value="Villas del Sur">Villas del Sur</option>
            <option value="Villas del Valle">Villas del Valle</option>
            <option value="Villas de Pradera Dorada">Villas de Pradera Dorada</option>
            <option value="Villas de Salvarcar">Villas de Salvarcar</option>
            <option value="Villas de Senecu">Villas de Senecu</option>
            <option value="Villas Primavera">Villas Primavera</option>
            <option value="Villas San Angel A y B">Villas San Angel A y B</option>
            <option value="Villas San Jose">Villas San Jose</option>
            <option value="Villas San Marcos">Villas San Marcos</option>
            <option value="Villas San Rafael">Villas San Rafael</option>
            <option value="Villas Santa Fe">Villas Santa Fe</option>
            <option value="Villas Santa Teresa">Villas Santa Teresa</option>
            <option value="Villas Solares">Villas Solares</option>
            <option value="Villas Vista del Sol">Villas Vista del Sol</option>
            <option value="Vista de la Cumbre I, II, III">Vista de la Cumbre I, II, III</option>
            <option value="Vista del Norte">Vista del Norte</option>
            <option value="Vista del Sol">Vista del Sol</option>
            <option value="Vista del Valle">Vista del Valle</option>
            <option value="Vista Hermosa">Vista Hermosa</option>
            <option value="Vistas de la Aurora">Vistas de la Aurora</option>
            <option value="Vistas del Bravo I">Vistas del Bravo I</option>
            <option value="Vistas del Bravo II">Vistas del Bravo II</option>
            <option value="Vistas del Bravo III">Vistas del Bravo III</option>
            <option value="Vistas de Zaragoza">Vistas de Zaragoza</option>
            <option value="Waterfill Rio Bravo">Waterfill Rio Bravo</option>
            <option value="Yolanda">Yolanda</option>
            <option value="Zacatecas">Zacatecas</option>
            <option value="Zaragoza">Zaragoza</option>
            <option value="Zuri">Zuri</option>
        </select>

    </main>
    <footer>
        <!-- place footer here -->
    </footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>

    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
</body>

</html>